name 'data-bag-faker'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures data-bag-faker'
long_description 'Installs/Configures data-bag-faker'
version '0.1.0'
